flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HDBC-sqlite3-2.3.3.1
- attoparsec-0.13.2.0
- yeshql-3.0.1.3
- servant-elm-0.4.0.1
- wai-app-static-3.1.6.1
- directory-1.3.1.5
- parallel-io-0.3.3
resolver: lts-9.9
