flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HDBC-sqlite3-2.3.3.1
- attoparsec-0.13.2.0
- yeshql-3.0.1.3
- servant-elm-0.4.0.1
- wai-app-static-3.1.6.1
- directory-1.3.1.5
- async-2.1.1.1
- megaparsec-6.2.0
- config-ini-0.2.1.1
- bytestring-0.10.8.2
resolver: lts-9.9
